apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cba.proxy.prismaaccess.com
spec:
  hosts:
    - cba.proxy.prismaaccess.com
  location: MESH_EXTERNAL
  ports:
    - number: 8080
      name: http
      protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-com
spec:
  hosts:
    - www.google.com
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-com-via-egress-gateway
spec:
  hosts:
    - www.google.com
  gateways:
    - istio-egressgateway
    - mesh
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.default.svc.cluster.local
            port:
              number: 80
    - match:
        - gateways:
            - istio-egressgateway
          port: 80
      route:
        - destination:
            host: cba.proxy.prismaaccess.com
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tunnel-tls
spec:
  host: cba.proxy.prismaaccess.com
  trafficPolicy:
    tunnel:
      protocol: CONNECT
      targetPort: 8080
      targetHost: cba.proxy.prismaaccess.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - www.google.com