version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./my-nginx.mesh-external.svc.cluster.local.crt:/etc/nginx-server-certs/tls.crt:ro
      - ./my-nginx.mesh-external.svc.cluster.local.key:/etc/nginx-server-certs/tls.key:ro
      - ./example.com.crt:/etc/nginx-ca-certs/example.com.crt:ro
  nginx-simple:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro