apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: client-credential-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: client-credential-role
subjects:
- kind: ServiceAccount
  name: curl
  namespace: default
