apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: default
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  http:
    - match:
        - headers:
            x-zeta-inhouse-required:
              exact: "true"
      rewrite:
        uri: "/"
        authority: httpbin.org
      route:
        - destination:
            host: httpbin.org
            port: 
              number: 80
    - match:
        - headers:
            x-zeta-inhouse-required:
              exact: "false"
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: cnn
            port:
              number: 443
    - name: default
      route:
      - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: cnn
            port:
              number: 443
  exportTo:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
  namespace: default
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          sni: edition.cnn.com
  exportTo:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: force-tunneling-mesh
  namespace: default
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  tls:
  - match:
    - sniHosts:
        - edition.cnn.com
    route:
    - destination:
        host: host.docker.internal
        subset: tunnel-traffic-to-cnn
        port:
          number: 8888
  exportTo:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-to-connect-proxy-and-tunnel-traffic-to-google-com
  namespace: default
spec:
  host: host.docker.internal
  subsets:
  - name: tunnel-traffic-to-cnn
    trafficPolicy:
      tunnel:
        targetHost: edition.cnn.com
        targetPort: 443
        protocol: CONNECT
  exportTo:
    - "*"
---